image: maven:3-openjdk-14

stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

maven-build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

maven-test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    expire_in: 30 days
    paths:
      - target/surefire-reports/TEST-*.xml
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
